### ISSUE TITLE
Does nothing?

### ISSUE THREAD

**Issue by Gruntfuggly** [baliscript/vscode-lineblame#1]
I've tried reloading, but nothing happens.

**Comment by veedrin** [comment]
@Gruntfuggly Should show blame annotations when you are in a git repo. Were you operating in a git repo?

**Comment by Gruntfuggly** [comment]
It's working on a javascript project, but not in my C++ projects? I'll try to work out what is different.

It's nice and fast where it is working though. :grin:

**Comment by Gruntfuggly** [comment]
I've noticed that the annotation only appear when the cursor is at the end of the line. Is that expected?

**Comment by veedrin** [comment]
I will fix that, thanks!

**Comment by Gruntfuggly** [comment]
I've found a bug. When typing, the following happened:

![image](https://user-images.githubusercontent.com/376658/57527013-dae67a80-7326-11e9-93ef-2da52cc11c12.png)

**Comment by veedrin** [comment]
It's settled since v0.0.4, enjoy coding.

**Comment by Gruntfuggly** [comment]
It's better, but there is still something not quite right:
![image](https://user-images.githubusercontent.com/376658/57534948-12f6b900-7339-11e9-8f28-5e61fa9e7bb0.png)
There are left over annotations, and the cursor is on line 63 with no annotation.

**Comment by veedrin** [comment]
Continuous improving 🙃

**Comment by Gruntfuggly** [comment]
I think you might need to call dispose() on your decorations - it looks like your disposeFunction just sets the decorations to an empty array. I think this leaves the decorations in memory still.

**Comment by Gruntfuggly** [comment]
In my extension, I store the all the decorations in an array and before calling setDecorations, I dispose all the current ones first.
