### ISSUE TITLE
装了没效果

### ISSUE THREAD

**Issue by wumingluren** [baliscript/vscode-lineblame#2]
安装的最新版，vscode 也是最新版，安装后重启，没效果，重新提交 git 也还是没效果

**Comment by wumingluren** [comment]
或者是不支持 vue 项目？

**Comment by wumingluren** [comment]
gitlens 使用这个插件是正常显示的

**Comment by veedrin** [comment]
这跟 vue 没关系的。有什么报错信息吗？或者试试其他的 Git 项目看能不能行？
多谢反馈，但我需要更多信息。

**Comment by wumingluren** [comment]
没看到哪里报错信息，换了其他项目也还是不显示

**Comment by veedrin** [comment]
可以把 vscode 的界面完整截个图给我吗？

**Comment by wumingluren** [comment]
![34VGC KT2S%G2PE7JZLEDS9](https://user-images.githubusercontent.com/41581133/58225127-3c5d0f00-7d53-11e9-9e4a-b8330c67498c.png)

**Comment by veedrin** [comment]
抱歉，实在不知道什么原因。
